config/routes.rb
AllergyHelper::Application.routes.draw do
  resources :reactions

  resources :foods

end

app/models/food.rb
class Food < ActiveRecord::Base
end

app/models/reaction.rb
class Reaction < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # GET /foods
  # GET /foods.xml
  def index
    @foods = Food.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @foods }
    end
  end

  # GET /foods/1
  # GET /foods/1.xml
  def show
    @food = Food.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @food }
    end
  end

  # GET /foods/new
  # GET /foods/new.xml
  def new
    @food = Food.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @food }
    end
  end

  # GET /foods/1/edit
  def edit
    @food = Food.find(params[:id])
  end

  # POST /foods
  # POST /foods.xml
  def create
    @food = Food.new(params[:food])

    respond_to do |format|
      if @food.save
        format.html { redirect_to(@food, :notice => 'Food was successfully created.') }
        format.xml  { render :xml => @food, :status => :created, :location => @food }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @food.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /foods/1
  # PUT /foods/1.xml
  def update
    @food = Food.find(params[:id])

    respond_to do |format|
      if @food.update_attributes(params[:food])
        format.html { redirect_to(@food, :notice => 'Food was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @food.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.xml
  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    respond_to do |format|
      format.html { redirect_to(foods_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  # GET /reactions
  # GET /reactions.xml
  def index
    @reactions = Reaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reactions }
    end
  end

  # GET /reactions/1
  # GET /reactions/1.xml
  def show
    @reaction = Reaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @reaction }
    end
  end

  # GET /reactions/new
  # GET /reactions/new.xml
  def new
    @reaction = Reaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @reaction }
    end
  end

  # GET /reactions/1/edit
  def edit
    @reaction = Reaction.find(params[:id])
  end

  # POST /reactions
  # POST /reactions.xml
  def create
    @reaction = Reaction.new(params[:reaction])

    respond_to do |format|
      if @reaction.save
        format.html { redirect_to(@reaction, :notice => 'Reaction was successfully created.') }
        format.xml  { render :xml => @reaction, :status => :created, :location => @reaction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @reaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reactions/1
  # PUT /reactions/1.xml
  def update
    @reaction = Reaction.find(params[:id])

    respond_to do |format|
      if @reaction.update_attributes(params[:reaction])
        format.html { redirect_to(@reaction, :notice => 'Reaction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @reaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reactions/1
  # DELETE /reactions/1.xml
  def destroy
    @reaction = Reaction.find(params[:id])
    @reaction.destroy

    respond_to do |format|
      format.html { redirect_to(reactions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meal %><br />
    <%= f.text_field :meal %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_field :ingredients %>
  </div>
  <div class="field">
    <%= f.label :time_eaten %><br />
    <%= f.datetime_select :time_eaten %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<h1>Listing foods</h1>

<table>
  <tr>
    <th>Meal</th>
    <th>Ingredients</th>
    <th>Time eaten</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @foods.each do |food| %>
  <tr>
    <td><%= food.meal %></td>
    <td><%= food.ingredients %></td>
    <td><%= food.time_eaten %></td>
    <td><%= link_to 'Show', food %></td>
    <td><%= link_to 'Edit', edit_food_path(food) %></td>
    <td><%= link_to 'Destroy', food, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Meal:</b>
  <%= @food.meal %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @food.ingredients %>
</p>

<p>
  <b>Time eaten:</b>
  <%= @food.time_eaten %>
</p>


<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AllergyHelper</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reactions/_form.html.erb
<%= form_for(@reaction) do |f| %>
  <% if @reaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reaction.errors.count, "error") %> prohibited this reaction from being saved:</h2>

      <ul>
      <% @reaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :severity %><br />
    <%= f.text_field :severity %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :time_first_observed %><br />
    <%= f.datetime_select :time_first_observed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reactions/edit.html.erb
<h1>Editing reaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @reaction %> |
<%= link_to 'Back', reactions_path %>

app/views/reactions/index.html.erb
<h1>Listing reactions</h1>

<table>
  <tr>
    <th>Severity</th>
    <th>Description</th>
    <th>Time first observed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reactions.each do |reaction| %>
  <tr>
    <td><%= reaction.severity %></td>
    <td><%= reaction.description %></td>
    <td><%= reaction.time_first_observed %></td>
    <td><%= link_to 'Show', reaction %></td>
    <td><%= link_to 'Edit', edit_reaction_path(reaction) %></td>
    <td><%= link_to 'Destroy', reaction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reaction', new_reaction_path %>

app/views/reactions/new.html.erb
<h1>New reaction</h1>

<%= render 'form' %>

<%= link_to 'Back', reactions_path %>

app/views/reactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Severity:</b>
  <%= @reaction.severity %>
</p>

<p>
  <b>Description:</b>
  <%= @reaction.description %>
</p>

<p>
  <b>Time first observed:</b>
  <%= @reaction.time_first_observed %>
</p>


<%= link_to 'Edit', edit_reaction_path(@reaction) %> |
<%= link_to 'Back', reactions_path %>